apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-server
  labels:
    app: app
spec:
  replicas: 1
  minReadySeconds: 30
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        lifecycle:
          preStop:
            exec:
              command: [ "/bin/sleep", "20" ]
        image: 172.20.102.190:5000/server:latest
        ports:
        - containerPort: 15500
        volumeMounts:
        - name: varlog
          mountPath: /home/coral/gamedata/log
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "2000m"
      restartPolicy: Always
      volumes:
      - name: varlog
        emptyDir: {}
