apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd
data:
  fluent.conf: |
    <source>
      @type tail
      path /var/log/containers/app-deployment-*.log
      pos_file /var/log/app-deployment.log.pos
      tag app.access
      <parse>
        @type json
      </parse>
    </source>
    
    <match app.access>
      @type forward
      send_timeout 5s
      recover_wait 2s
      hard_timeout 5s
      <server>
        name app.agent
        host host.docker.internal
        port 12112
      </server>
    </match>
