apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  selector:
    app: app
  ports:
    - protocol: TCP
      port: 15500
      targetPort: 15500
      nodePort: 30002
  type: LoadBalancer
