version: '3.3'
services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.2
    container_name: elasticsearch
    environment:
    - bootstrap.memory_lock=true
    - "ES_JAVA_OPTS=-Xms1048m -Xmx1048m"
    - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
    - .\ElasticSearch\data:/usr/share/elasticsearch/data
    ports:
    - "9200:9200"
    expose:
    - 9200
    
  kibana:
    image: docker.elastic.co/kibana/kibana:7.4.2
    ports:
    - "5601:5601"
    environment:
      SERVER_HOST: 0.0.0.0
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
      
  registry:
    restart: always
    image: registry:2
    ports:
    - 5000:5000
    volumes:
    - .\DockerRegistry\config.yml:/etc/docker/registry/config.yml
    - .\DockerRegistry\data:/var/lib/registry
    
  mysql5.7:
    image: mysql:5.7.28
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: coral
    ports:
    - 3306:3306
    volumes:
    - .\Mysql5.7\Data:/var/lib/mysql
    - .\Mysql5.7\:/etc/mysql/
    
  mysql8.x:
    image: mysql:8.0.18
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: coral
    ports:
    - 3307:3306
    volumes:
    - .\Mysql8.x\Data:/var/lib/mysql
    - .\Mysql8.x\:/etc/mysql/

  redis:
    image: 'redis:5.0.7'
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    ports:
    - 6379:6379
    volumes:
    - .\Redis\Data:/data
    - .\Redis\redis.conf:/usr/local/etc/redis/redis.conf
    
